### ISSUE TITLE
Droping traps using hotkey produces no sound

### ISSUE THREAD

**Issue by dennwc** [noxworld-dev/opennox#369]

**Comment by al0fdf** [comment]
Can not reproduce with commit 9a17cf0c1

https://github.com/noxworld-dev/opennox/assets/104121665/3251d8fd-8fc5-4c6b-b230-d339078c60d7

**Comment by dennwc** [comment]
Thank you for checking! Is it the same in multiplayer?

**Comment by al0fdf** [comment]
> Thank you for checking! Is it the same in multiplayer?

That was multiplayer...? If you're talking about single player, I haven't made it up to that part in Solo Mode yet as a wizard.

**Comment by KILAH4716** [comment]
I've been able to easily replicate it in my version: v1.8.11.

In Vanilla Nox, there's a limit to how many sounds can be played at once, and if the number of sounds playing has reached the game's limit, then some sounds will simply not play. Also there are some sections of some maps (most of them custom) that have polygon errors that forbid many sounds from being played. Prime example, the massive bridge section in the Swamp Quest map.

OpenNox and NoxReloaded both may have fixes that might have expanded the limit to sounds being played and made a few subtle sound reworks that made a significant difference. I THINK it's fixed for OpenNox, because I tested the sound limit as well.

I'm upload a video to my YouTube channel. Will post it here shortly.

**Comment by KILAH4716** [comment]
https://www.youtube.com/watch?v=56kROHjCUtU

**Comment by dennwc** [comment]
This proves that it was broken in the latest stable release at least.

So we only need to check that it now works in Solo in current `dev` (since al0fdf demonstrated that it works in MP now).

**Comment by dennwc** [comment]
Can't reproduce on `dev`. So it's fixed indeed!
